baseURL = "https://therapish.org/"
languageCode = "en-us"
title = "Therapish"
theme = "mainroad"

# number of posts to show on home/category/tag pages (Default: 10)
paginate = 5

# optionally override the site's footer with custom copyright text
# copyright = "Except where otherwise noted, content on this site is licensed under a [Creative Commons Attribution 4.0 International license](https://creativecommons.org/licenses/by-sa/4.0/)."
#googleAnalytics = "UA-123-45"
#disqusShortname = "XYW"

[permalinks]
  post = "/:year/:month/:title/"
  page = "/:slug/"

[[menu.navbar]]
  name = "About"
  url = "/about"

[Author]
  name = "Robert James Joy"
  legal_name = "Robert James Miller"

# Theme variables
#
[params]
  # Description/subtitle for homepage (can be Markdown)

  # Format dates with Go's time formatting
  date_format = "Mon Jan 02, 2006"

  [params.widgets]
    recent_articles = true
    recent_articles_num = 4

# Default content language for Hugo 0.17's multilingual support (default is "en")
# See: https://github.com/spf13/hugo/blob/master/docs/content/content/multilingual.md
#DefaultContentLanguage = "en"

# Languages to render
#[languages.en]
#[languages.bg]

# vim: ts=2 sw=2 et
